name: <Base> Reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: cd layers/base && bun install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          workdir: layers/base/
          eslint_flags: 'app/'
