name: <openapi-zod-client> Reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: layers/openapi-zod-client
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          workdir: layers/openapi-zod-client/
          eslint_flags: 'tasks/'
